route:
  group_wait: 20s
  group_interval: 20s
  repeat_interval: 15m
  group_by: ['alertname', 'cluster', 'service']
  receiver: alertmanager-bot

receivers:
- name: alertmanager-bot
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'