version: "3"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  bot_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9095:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped
    networks:
      - monitoring
  near-exporter:
    image: masknetgoal634/near-prometheus-exporter:latest
    container_name: near-exporter
    ports:
      - 9333:9333
    networks:
      - monitoring
  coingecko-exporter:
    image: ruanbekker/coingecko-exporter
    container_name: coingecko-exporter
    environment:
      - CRYPTO_COINS=near
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - monitoring
  alertmanager-bot:
    command:
    - --alertmanager.url=http://alertmanager:9093
    - --log.level=info
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: "1933874030"
      TELEGRAM_TOKEN: 2132175026:AAHvN6jPaRgXhvj1lAiT7RgirPkfpOz3a2o 
    image: metalmatze/alertmanager-bot:0.4.3
    container_name: alertmanager-bot
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./data:/data
    networks:
    - monitoring