# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "alert_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['xxxxxxxxx:9095'] # replace xxxxx with ip address

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['nodeexporter:9100'] 
      labels:
        label: "testnet"
    - targets: ['xxxxxxxxxx:9111'] # replace xxxxx with ip address
      labels:
        label: "guildnet"
    - targets: ['xxxxxxxxxxx:9111'] # replace xxxxx with ip address
      labels:
        label: "mainnet"
        
  - job_name: near-exporter
    scrape_interval: 15s
    static_configs:
    - targets: ['xxxxxxxxxxxxx:9333'] # replace xxxxx with ip address
      labels:
        label: "testnet"
    - targets: ['xxxxxxxxxxx:9333'] # replace xxxxx with ip address
      labels:
        label: "guildnet"
    - targets: ['xxxxxxxxxxx:9333'] # replace xxxxx with ip address
      labels:
        label: "mainnet"

  - job_name: near-client
    scrape_interval: 15s
    static_configs:
    - targets: ['xxxxxxxxxxxxxx:3030'] # replace xxxxx with ip address
      labels:
        label: "testnet"
    - targets: ['xxxxxxxxxxxxxx:3030'] # replace xxxxx with ip address
      labels:
        label: "guildnet"
    - targets: ['xxxxxxxxxxxxxx:3030'] # replace xxxxx with ip address
      labels:
        label: "mainnet"

  - job_name: coingecko
    scrape_interval: 15s
    static_configs:
    - targets: ['xxxxxxxxxxxxxxxx:5000'] # replace xxxxx with ip address
     
